<<<<<<< HEAD
server.port=2027
=======
server.port=2023
>>>>>>> 009e1075893fd8e08b754a29550a8f2261be7434
spring.thymeleaf.prefix=classpath:/templates/
spring.thymeleaf.suffix=.jsp
spring.datasource.url=jdbc:mysql://localhost:3306/klu
spring.datasource.username=root
spring.datasource.password=admin
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.jpa.hibernate.ddl-auto=update



